// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// asmbPLS_fit_rcpp
List asmbPLS_fit_rcpp(arma::mat E_matrix, arma::mat F_matrix, int PLS_term, NumericVector X_dim, arma::mat percent);
RcppExport SEXP _asmbPLS_asmbPLS_fit_rcpp(SEXP E_matrixSEXP, SEXP F_matrixSEXP, SEXP PLS_termSEXP, SEXP X_dimSEXP, SEXP percentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E_matrix(E_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type F_matrix(F_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type PLS_term(PLS_termSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X_dim(X_dimSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type percent(percentSEXP);
    rcpp_result_gen = Rcpp::wrap(asmbPLS_fit_rcpp(E_matrix, F_matrix, PLS_term, X_dim, percent));
    return rcpp_result_gen;
END_RCPP
}
// asmbPLS_predict_rcpp
arma::mat asmbPLS_predict_rcpp(arma::mat newdata, int PLS_term_selected, List asmbPLS_results);
RcppExport SEXP _asmbPLS_asmbPLS_predict_rcpp(SEXP newdataSEXP, SEXP PLS_term_selectedSEXP, SEXP asmbPLS_resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< int >::type PLS_term_selected(PLS_term_selectedSEXP);
    Rcpp::traits::input_parameter< List >::type asmbPLS_results(asmbPLS_resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(asmbPLS_predict_rcpp(newdata, PLS_term_selected, asmbPLS_results));
    return rcpp_result_gen;
END_RCPP
}
// mbPLS_fit_rcpp
List mbPLS_fit_rcpp(arma::mat E_matrix, arma::mat F_matrix, int PLS_term, NumericVector X_dim);
RcppExport SEXP _asmbPLS_mbPLS_fit_rcpp(SEXP E_matrixSEXP, SEXP F_matrixSEXP, SEXP PLS_termSEXP, SEXP X_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E_matrix(E_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type F_matrix(F_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type PLS_term(PLS_termSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X_dim(X_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(mbPLS_fit_rcpp(E_matrix, F_matrix, PLS_term, X_dim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_asmbPLS_asmbPLS_fit_rcpp", (DL_FUNC) &_asmbPLS_asmbPLS_fit_rcpp, 5},
    {"_asmbPLS_asmbPLS_predict_rcpp", (DL_FUNC) &_asmbPLS_asmbPLS_predict_rcpp, 3},
    {"_asmbPLS_mbPLS_fit_rcpp", (DL_FUNC) &_asmbPLS_mbPLS_fit_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_asmbPLS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
