# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asmbPLS_fit_rcpp <- function(E_matrix, F_matrix, PLS_term, X_dim, percent) {
    .Call(`_asmbPLS_asmbPLS_fit_rcpp`, E_matrix, F_matrix, PLS_term, X_dim, percent)
}

asmbPLS_predict_rcpp <- function(newdata, PLS_term_selected, asmbPLS_results) {
    .Call(`_asmbPLS_asmbPLS_predict_rcpp`, newdata, PLS_term_selected, asmbPLS_results)
}

mbPLS_fit_rcpp <- function(E_matrix, F_matrix, PLS_term, X_dim) {
    .Call(`_asmbPLS_mbPLS_fit_rcpp`, E_matrix, F_matrix, PLS_term, X_dim)
}

