# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CV_index <- function(Y_indicator, K_input, seed, only_observe) {
    .Call(`_asmbPLS_CV_index`, Y_indicator, K_input, seed, only_observe)
}

CV_index_binary <- function(F_matrix, K_input) {
    .Call(`_asmbPLS_CV_index_binary`, F_matrix, K_input)
}

CV_index_morethan2levels <- function(F_matrix, K_input) {
    .Call(`_asmbPLS_CV_index_morethan2levels`, F_matrix, K_input)
}

Euclidean_distance <- function(matrix_fit, matrix_predict, F_matrix, outcome_type) {
    .Call(`_asmbPLS_Euclidean_distance`, matrix_fit, matrix_predict, F_matrix, outcome_type)
}

Mahalanobis_distance <- function(matrix_fit, matrix_predict, F_matrix, outcome_type) {
    .Call(`_asmbPLS_Mahalanobis_distance`, matrix_fit, matrix_predict, F_matrix, outcome_type)
}

PCA_Mahalanobis_distance <- function(Y_fit, Y_predict) {
    .Call(`_asmbPLS_PCA_Mahalanobis_distance`, Y_fit, Y_predict)
}

Results_comparison_MSE <- function(Y_predict, Y_true) {
    .Call(`_asmbPLS_Results_comparison_MSE`, Y_predict, Y_true)
}

Results_comparison_accuracy <- function(Y_predict, Y_true) {
    .Call(`_asmbPLS_Results_comparison_accuracy`, Y_predict, Y_true)
}

asmbPLSDA_CV <- function(E_matrix, F_matrix, PLS_term, X_dim, quantile_table, outcome_type, Method, K, ncv, center = NULL, scale = NULL) {
    .Call(`_asmbPLS_asmbPLSDA_CV`, E_matrix, F_matrix, PLS_term, X_dim, quantile_table, outcome_type, Method, K, ncv, center, scale)
}

asmbPLSDA_binary_fit <- function(E_matrix, F_matrix, PLS_term, X_dim, percent, center = NULL, scale = NULL) {
    .Call(`_asmbPLS_asmbPLSDA_binary_fit`, E_matrix, F_matrix, PLS_term, X_dim, percent, center, scale)
}

asmbPLSDA_fit <- function(X_matrix, Y_matrix, PLS_term, X_dim, percent, outcome_type, center = NULL, scale = NULL) {
    .Call(`_asmbPLS_asmbPLSDA_fit`, X_matrix, Y_matrix, PLS_term, X_dim, percent, outcome_type, center, scale)
}

asmbPLSDA_morethantwo_fit <- function(E_matrix, F_matrix, PLS_term, X_dim, percent, center = NULL, scale = NULL) {
    .Call(`_asmbPLS_asmbPLSDA_morethantwo_fit`, E_matrix, F_matrix, PLS_term, X_dim, percent, center, scale)
}

asmbPLSDA_predict <- function(asmbPLSDA_results, newdata, PLS_term_selected, Method = NULL) {
    .Call(`_asmbPLS_asmbPLSDA_predict`, asmbPLSDA_results, newdata, PLS_term_selected, Method)
}

asmbPLS_CV <- function(E_matrix, F_matrix, PLS_term, X_dim, quantile_table, Y_indicator, K = NULL, only_observe = NULL, seed = NULL) {
    .Call(`_asmbPLS_asmbPLS_CV`, E_matrix, F_matrix, PLS_term, X_dim, quantile_table, Y_indicator, K, only_observe, seed)
}

asmbPLS_fit <- function(E_matrix, F_matrix, PLS_term, X_dim, percent) {
    .Call(`_asmbPLS_asmbPLS_fit`, E_matrix, F_matrix, PLS_term, X_dim, percent)
}

asmbPLS_predict <- function(asmbPLS_results, newdata, PLS_term_selected) {
    .Call(`_asmbPLS_asmbPLS_predict`, asmbPLS_results, newdata, PLS_term_selected)
}

mbPLS_fit <- function(E_matrix, F_matrix, PLS_term, X_dim) {
    .Call(`_asmbPLS_mbPLS_fit`, E_matrix, F_matrix, PLS_term, X_dim)
}

quantile_f <- function(V, P) {
    .Call(`_asmbPLS_quantile_f`, V, P)
}

sample_group <- function(n, K_input) {
    .Call(`_asmbPLS_sample_group`, n, K_input)
}

stl_sort <- function(x) {
    .Call(`_asmbPLS_stl_sort`, x)
}

weight_sparse <- function(input, lambda) {
    .Call(`_asmbPLS_weight_sparse`, input, lambda)
}

